### PR TITLE
added better grass

### PR DESCRIPTION
**Pull request by 0PandaDEV**
Hey, I added better grass resource pack to the modpack because I think I would fit to the rest, but I don't know what the hash in the .pw.toml file is. What do I have to input there?

### CODE REVIEW

**Comment by NoSadBeHappy** [comment]
Hi! Thank you for your help. I am new to packwiz too, so @RedstoneWizard08 can you help. We are also planning on adding the ctm pack (https://www.curseforge.com/minecraft/texture-packs/connected-textures-mod-ctm-overhaul). Thank you!

**Comment by RedstoneWizard08** [comment]
Hi I'm here. I'll take a look at better grass.

**Comment by RedstoneWizard08** [comment]
> 

For getting the hash, if you have a linux machine, you can do:
```sh
curl -fsSL https://cdn.modrinth.com/data/SiVYAB4s/versions/hYiyqm7X/%C2%A7fBetter%20%C2%A7a%C2%A7lGrass%20%C2%A771.19.x.zip | sha1sum
```

**Comment by RedstoneWizard08** [comment]
I'm taking care of this anyway in `v2.0.0-beta5`. I'll add Better Grass in there for you. Thanks for your input!

**Comment by NoSadBeHappy** [comment]
Okay, so we have actually decided against adding better grass to the new version, as we are going to add continuity to the pack once there is a stable version for 1.19.3 (https://modrinth.com/mod/continuity). Continuity adds connected grass, which is basically a simular outcome. Thank you for your input!

**Comment by 0PandaDEV** [comment]
Ok but where did you read that Continuity adds connected grass and isn't that something else?

**Comment by NoSadBeHappy** [comment]
Homestly, im not sure it is, but if continuity doesen't have connected grass, we will use this mod.

https://modrinth.com/mod/lambdabettergrass

The point is, is that I think mods are better than resource packs for connected grass.

**Pull request closed without merging**
